sudo: false
language: python
python: 3.4
cache: pip
env:
  global:
    - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/python.org
install: pip install -r dev-requirements.txt
before_script:
  - psql -c 'create database "python.org";' -U postgres
script:
  - coverage run manage.py test -v2
  - coverage report --fail-under=75
notifications:
  irc:
    channels:
      - "irc.freenode.net#pydotorg"
    on_success: change
    on_failure: always
