name: Check collectstatic
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version-file: '.python-version'
      - name: Cache Python dependencies
        uses: actions/cache@v4
        env:
          cache-name: pythondotorg-cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('requirements/requirements.txt', 'requirements/*-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ github.job }}-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements/requirements.txt -r requirements/prod-requirements.txt
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/app
          cd app
          DJANGO_SETTINGS_MODULE=app.pydotorg.settings.static python manage.py collectstatic --noinput
